name: Build
on: 
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: pip install frida-tools
      - run: sudo pip install -r requirements.txt --upgrade
      - run: ./dump.py com.opera.gx
